server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: ${MICROSERVICE_NAME:qip-designtime-catalog}
  cloud:
    gateway:
      routes:
        - id: proxy-to-runtime
          uri: http://qip-runtime-catalog:8080
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}    # forward full path without prefix rewriting
management:
  endpoints:
    web:
      exposure:
        exclude: shutdown
        include: info, health, ready, env, loggers, metrics, prometheus

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
  config: classpath:logback-spring.xml
